### ISSUE TITLE
Tap listener on header cells

### ISSUE THREAD

**Issue by jllodra** [swluken/TouchTreeGrid#4]
Hi Steve,

do you know if it is possible to add a tap listener on header cells? So I could get its **column index** and **dataIndex** when tapping?

Thank you

**Comment by swluken** [comment]
I add tap listener if columnSorting = true in updateHeader() method.  See handleColumnSort() method for how to get dataIndex and colIndex.  You could perhaps override/extend updateHeader() method to call your own method in lieu of column sorting.

Regards,
Steve
